---
- hosts: localhost
  tasks: 
    - name: docker-compose
      docker_compose: 
        project_name: "wordpress"
        recreate: always
        definition:
          version: '3.5'
          services:
            db:
              image: mysql:5.7
              ports:
                - "3306:3306"
              restart: always
              environment:
                MYSQL_ROOT_PASSWORD: "dev123"
                MYSQL_DATABASE: "wp_app"
                MYSQL_USER: "dev"
                MYSQL_PASSWORD: "dev123"
            wordpress:
              container_name: "wp-app"
              depends_on:
                - db
              image: wordpress:latest
              restart: always
              environment:
                WORDPRESS_DB_HOST: db:3306
                WORDPRESS_DB_USER: "dev"
                WORDPRESS_DB_PASSWORD: "dev123"
                WORDPRESS_DB_NAME: "wp_app"
              volumes:
                - ./uploads.ini:/usr/local/etc/php/conf.d/uploads.ini
                - ./wordpress:/var/www/html
            swag:
              image: lscr.io/linuxserver/swag
              container_name: swag
              cap_add:
                - NET_ADMIN
              environment:
                - PUID=1000
                - PGID=1000
                - TZ=Asia/PhnomPenh
                - URL=sothy.tech
                - SUBDOMAINS=swag,
                - VALIDATION=http
                - ONLY_SUBDOMAINS=true #optional
                - CERTPROVIDER=zerossl
                - EMAIL=sothylorn@gmail.com
              depends_on:
                - wordpress
              volumes:
                - ./nginx/proxy-confs/default.conf:/config/nginx/site-confs/default.conf
              ports:
                - 443:443
                - 80:80 #optional
              restart: unless-stopped
