version: "3.3"

services:
  db:
    image: mysql:5.7
    # ports:
    #   - "${MYSQL_PORT}:3306"
    volumes:
      - db_data:/var/lib/mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USERNAME}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}


  wordpress:
    container_name: ${WP_CONTAINER_NAME}
    depends_on:
      - db
    image: wordpress:latest
    # ports:
      # - "${WORDPRESS_APP_PORT}:80"
      # - "8080:80"
    restart: always
    environment:
      WORDPRESS_DB_HOST: db:3306
      WORDPRESS_DB_USER: ${MYSQL_USERNAME}
      WORDPRESS_DB_PASSWORD: ${MYSQL_PASSWORD}
      WORDPRESS_DB_NAME: ${MYSQL_DATABASE}
    volumes:
      - ./uploads.ini:/usr/local/etc/php/conf.d/uploads.ini
      - ./wordpress:/var/www/html

  swag:
    image: lscr.io/linuxserver/swag
    container_name: swag
    cap_add:
      - NET_ADMIN
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Asia/PhnomPenh
      - URL=${DOMAIN_URL}
      - SUBDOMAINS=wildcard
      - VALIDATION=dns
      - ONLY_SUBDOMAINS=true #optional
      #- CERTPROVIDER=zerossl
      - DNSPLUGIN=cloudflare #optional
      # - DUCKDNSTOKEN=<token> #optional
      #- EMAIL=sothylorn@gmail.com
      # - DHLEVEL=2048 #optional
      # - EXTRA_DOMAINS=<extradomains> #optional
      # - STAGING=false #optional
    depends_on:
      - wordpress
    volumes:
      - ./nginx/proxy-confs/default.conf:/config/nginx/site-confs/default.conf
      - ./dns-conf/cloudflare.ini:/config/dns-conf/cloudflare.ini
    ports:
      - 443:443
      - 80:80 #optional
    restart: unless-stopped

volumes:
  db_data: {}